# RAKF admin commands - mbt v2 host build.  See project.toml.
# mbt is vendored as a git submodule at the repo root (../mbt); override
# MBT_ROOT to build against a different checkout.
MBT_ROOT ?= ../mbt
include $(MBT_ROOT)/mk/mbt.mk
